[project]
name = "battlebox"
version = "0.1.0"
description = "A program to manage a playable digital mtg battlebox deck."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
]

[dependency-groups]
dev = [
    "ruff>=0.9.3",
]
